version: '3.8'

services:
  mysql:
    ports:
      - "4020:3306"

  backend:
    environment:
      FRONTEND_URL: http://localhost:4000
    ports:
      - "4010:5000"

  frontend:
    ports:
      - "4000:80"



